/* Generated by scripts/convert-svg from src/assets/icons/ic-down.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Down = (props: IconProps): JSX.Element => (
  <svg width={20} height={20} viewBox="0 0 20 20" {...props}>
    <defs>
      <path id="prefix__a" d="M12.704 0L3 9.5l9.704 9.5 3.396-3.325L9.793 9.5 16.1 3.325z" />
    </defs>
    <use fill="#FA775E" fillRule="evenodd" transform="rotate(-90 9.55 9.5)" xlinkHref="#prefix__a" />
  </svg>
)

export default Down
