/* Generated by scripts/convert-svg from src/assets/icons/ic-menu.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Menu = (props: IconProps): JSX.Element => (
  <svg width={36} height={36} viewBox="0 0 36 36" {...props}>
    <defs>
      <path
        id="prefix__a"
        d="M25.667 18c1.288 0 2.333.895 2.333 2s-1.045 2-2.333 2H2.333C1.045 22 0 21.105 0 20s1.045-2 2.333-2h23.334zm0-18C26.955 0 28 .895 28 2s-1.045 2-2.333 2H2.333C1.045 4 0 3.105 0 2s1.045-2 2.333-2h23.334zm0 9C26.955 9 28 9.895 28 11s-1.045 2-2.333 2H2.333C1.045 13 0 12.105 0 11s1.045-2 2.333-2h23.334z"
      />
    </defs>
    <g fill="none" fillRule="evenodd" transform="translate(4 5)">
      <mask id="prefix__b" fill="#fff">
        <use xlinkHref="#prefix__a" />
      </mask>
      <use fill="#2165E2" xlinkHref="#prefix__a" />
      <g fill="#2165E2" fillRule="nonzero" mask="url(#prefix__b)">
        <path d="M-30.074-25h89v76h-89z" />
      </g>
    </g>
  </svg>
)

export default Menu
