/* Generated by scripts/convert-svg from src/assets/icons/ic-home.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Home = (props: IconProps): JSX.Element => (
  <svg width={36} height={36} viewBox="0 0 36 36" {...props}>
    <defs>
      <path
        id="prefix__a"
        d="M23.843 9.968L12.287.106a.442.442 0 00-.574 0L.157 9.968A.45.45 0 000 10.31v13.897C0 25.197.796 26 1.778 26H8c.245 0 .444-.2.444-.448V17.93h7.112v7.62c0 .248.199.449.444.449h6.222c.982 0 1.778-.803 1.778-1.793V10.31a.45.45 0 00-.157-.342z"
      />
    </defs>
    <g fill="none" fillRule="evenodd" transform="translate(6 4)">
      <mask id="prefix__b" fill="#fff">
        <use xlinkHref="#prefix__a" />
      </mask>
      <use fill="#00AEA7" xlinkHref="#prefix__a" />
      <g fill="#2165E2" fillRule="nonzero" mask="url(#prefix__b)">
        <path d="M-31-24h86v76h-86z" />
      </g>
    </g>
  </svg>
)

export default Home
