/* Generated by scripts/convert-svg from src/assets/icons/ic-ob.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Ob = (props: IconProps): JSX.Element => (
  <svg width={25} height={25} viewBox="0 0 25 25" {...props}>
    <g
      transform="translate(1 1)"
      stroke="#FFF"
      strokeWidth={2}
      fill="none"
      fillRule="evenodd"
      opacity={0.498}
      strokeLinecap="square"
    >
      <path d="M0 6.5h23v16H0z" />
      <ellipse cx={11.5} cy={14.5} rx={3.136} ry={3} />
      <path d="M3.136 3.5h16.728M7.318.5h8.364" />
    </g>
  </svg>
)

export default Ob
