/* Generated by scripts/convert-svg from src/assets/icons/ic-transfer-5.svg */
import * as React from 'react'
import Svg, { G, Path, Circle } from 'react-native-svg'
import { IconProps } from '../common'

const Transfer5 = (props: IconProps): JSX.Element => (
  <Svg width={22} height={24} viewBox="0 0 22 24" {...props}>
    <G transform="translate(0 .55)" fill="none">
      <Path
        d="M2 11.45a9 9 0 0117.04-4.048l1.786-.9A10.996 10.996 0 0011 .45c-6.075 0-11 4.925-11 11h2zm18 0a9 9 0 01-9 9 8.997 8.997 0 01-8.04-4.95l-1.786.9A10.996 10.996 0 0011 22.45c6.075 0 11-4.924 11-11h-2z"
        fill="#2165E2"
      />
      <Circle fill="#111" cx={11} cy={11.451} r={2} />
      <Path
        fill="#111"
        d="M13.19 5.151l-.266 1.982 7.93 1.062 1.06-7.93L19.934 0l-.796 5.947zM8.81 17.75l.266-1.982-7.93-1.061-1.06 7.93 1.981.265.796-5.947z"
      />
    </G>
  </Svg>
)

export default Transfer5
