/* Generated by scripts/convert-svg from src/assets/icons/ic-transfer-4.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Transfer4 = (props: IconProps): JSX.Element => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <g fill="none">
      <path fill="#2165E2" d="M3 19.2h18v-1.477H3zM3 6.277h18V4.8H3z" />
      <path
        d="M18 24H6a3 3 0 01-3-3V3a3 3 0 013-3h12a3 3 0 013 3v18a3 3 0 01-3 3zm1.5-3V3A1.5 1.5 0 0018 1.5H6A1.5 1.5 0 004.5 3v18A1.5 1.5 0 006 22.5h12a1.5 1.5 0 001.5-1.5z"
        fill="#111"
      />
    </g>
  </svg>
)

export default Transfer4
