/* Generated by scripts/convert-svg from src/assets/icons/ic-pin-back.svg */
import * as React from 'react'
import Svg, { Defs, Path, G, Mask, Use } from 'react-native-svg'
import { IconProps } from '../common'

const PinBack = (props: IconProps): JSX.Element => (
  <Svg width={80} height={80} viewBox="0 0 80 80" {...props}>
    <Defs>
      <Path id="prefix__a" d="M49.148 6L15 40.5 49.148 75 61.1 62.925 38.904 40.5 61.1 18.075z" />
    </Defs>
    <G fill="none" fillRule="evenodd">
      <Mask id="prefix__b" fill="#fff">
        <Use xlinkHref="#prefix__a" />
      </Mask>
      <Use
        fill="#9BA1A1"
        stroke="#9BA1A1"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={4}
        xlinkHref="#prefix__a"
      />
      <G fill="#9BA1A1" fillRule="nonzero" mask="url(#prefix__b)">
        <Path d="M0 0h86v86H0z" />
      </G>
    </G>
  </Svg>
)

export default PinBack
