/* Generated by scripts/convert-svg from src/assets/icons/ic-x.svg */
import * as React from 'react'
import { IconProps } from '../common'

const X = (props: IconProps): JSX.Element => (
  <svg width={20} height={20} viewBox="0 0 20 20" {...props}>
    <defs>
      <path
        d="M7.148 9.855L2 4.8 4.852 2 10 7.055 15.148 2 18 4.8l-5.148 5.055L13 10l-.148.145L18 15.2 15.148 18 10 12.945 4.852 18 2 15.2l5.148-5.055L7 10l.148-.145z"
        id="prefix__a"
      />
    </defs>
    <use fill="#2165E2" xlinkHref="#prefix__a" fillRule="evenodd" />
  </svg>
)

export default X
