/* Generated by scripts/convert-svg from src/assets/icons/ic-chevron.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Chevron = (props: IconProps): JSX.Element => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <path d="M9.444 20L8 18.761 13.796 12 8 5.239 9.444 4l6.327 7.382a.95.95 0 010 1.237L9.444 20z" fill="#111" />
  </svg>
)

export default Chevron
