/* Generated by scripts/convert-svg from src/assets/icons/ic-transfer-6.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Transfer6 = (props: IconProps): JSX.Element => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <g fill="none">
      <path
        d="M2.423 11.905c.005-4.719 3.354-8.777 7.999-9.693 4.644-.916 9.291 1.565 11.1 5.926a9.875 9.875 0 01-3.664 12.007 9.949 9.949 0 01-12.531-1.237l-1.08 1.077a11.48 11.48 0 0014.459 1.427 11.394 11.394 0 004.228-13.856C20.847 2.524 15.484-.339 10.125.718 4.765 1.775.901 6.458.895 11.904l1.528.001z"
        fill="#111"
      />
      <path fill="#2165E2" d="M13.118 4.29H11.59v8.376h8.403v-1.523h-6.875z" />
      <path d="M1.958 23.342l6.744-6.721L0 14.666l1.958 8.676zm.063-6.661l3.64.818-2.82 2.81-.82-3.628z" fill="#111" />
    </g>
  </svg>
)

export default Transfer6
