/* Generated by scripts/convert-svg from src/assets/icons/budgetpath.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Budgetpath = (props: IconProps): JSX.Element => (
  <svg width={381} height={108} viewBox="0 0 381 108" {...props}>
    <defs>
      <filter x="-10.1%" y="-34.4%" width="120.3%" height="197.6%" filterUnits="objectBoundingBox" id="prefix__a">
        <feMorphology radius={3.5} operator="dilate" in="SourceAlpha" result="shadowSpreadOuter1" />
        <feOffset dy={10} in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
        <feMorphology radius={3.5} in="SourceAlpha" result="shadowInner" />
        <feOffset dy={10} in="shadowInner" result="shadowInner" />
        <feComposite in="shadowOffsetOuter1" in2="shadowInner" operator="out" result="shadowOffsetOuter1" />
        <feGaussianBlur stdDeviation={8} in="shadowOffsetOuter1" result="shadowBlurOuter1" />
        <feColorMatrix
          values="0 0 0 0 0.768627451 0 0 0 0 0.862745098 0 0 0 0 0.239215686 0 0 0 0.4 0"
          in="shadowBlurOuter1"
        />
      </filter>
      <path
        id="prefix__b"
        d="M18 51.975L37.394 49l22.933 11.203 9.91-3.565 12.257 14.645 10.92-4.83 17.48-4.646 7.002 2.463 18.002 3.712 7.191-1.53 11.583 1.53 13.798 3.3 17.146 8.096h22.953l27.536 13.97 10.763 23.381 14.27 1.968h17.382l5.145-14.165 5.911-6.747 21.524 12.96 11.053-4.3 11.689 8.48 26.723-11.649"
      />
    </defs>
    <g transform="translate(1 -40)" fill="none" fillRule="evenodd" strokeLinecap="round" strokeLinejoin="round">
      <use fill="#000" filter="url(#prefix__a)" xlinkHref="#prefix__b" />
      <use stroke="#FA775E" strokeWidth={4} xlinkHref="#prefix__b" />
    </g>
  </svg>
)

export default Budgetpath
