/* Generated by scripts/convert-svg from src/assets/icons/budgetpath.svg */
import * as React from 'react'
import Svg, { Defs, Path, G, Use } from 'react-native-svg'
/* SVGR has dropped some elements not supported by react-native-svg: filter */

import { IconProps } from '../common'

const Budgetpath = (props: IconProps): JSX.Element => (
  <Svg width={381} height={108} viewBox="0 0 381 108" {...props}>
    <Defs>
      <Path
        id="prefix__b"
        d="M18 51.975L37.394 49l22.933 11.203 9.91-3.565 12.257 14.645 10.92-4.83 17.48-4.646 7.002 2.463 18.002 3.712 7.191-1.53 11.583 1.53 13.798 3.3 17.146 8.096h22.953l27.536 13.97 10.763 23.381 14.27 1.968h17.382l5.145-14.165 5.911-6.747 21.524 12.96 11.053-4.3 11.689 8.48 26.723-11.649"
      />
    </Defs>
    <G transform="translate(1 -40)" fill="none" fillRule="evenodd" strokeLinecap="round" strokeLinejoin="round">
      <Use fill="#000" xlinkHref="#prefix__b" />
      <Use stroke="#FA775E" strokeWidth={4} xlinkHref="#prefix__b" />
    </G>
  </Svg>
)

export default Budgetpath
