/* Generated by scripts/convert-svg from src/assets/icons/ic-polaris.svg */
import * as React from 'react'
import Svg, { Path } from 'react-native-svg'
import { IconProps } from '../common'

const Polaris = (props: IconProps): JSX.Element => (
  <Svg width={25} height={24} viewBox="0 0 25 24" {...props}>
    <Path
      d="M15.374 15.533l4.733 5.354-1.735.848-3.489-4.473 1.452 5.468-1.682.821-1.379-6.992 2.1-1.026zm-6.23-.04l2.1 1.027-1.299 7.031-1.734-.847 1.37-5.507-3.408 4.511-1.681-.82 4.652-5.394zm15.217-4.151l-.434 1.883-5.666-.099 5.156 2.311-.42 1.826-6.294-3.327.525-2.28 7.133-.314zm-24.124 0l7.113.227.526 2.28-6.274 3.414-.434-1.884 5.136-2.398-5.646.186-.42-1.825zM19.501 2.02l1.215 1.502-3.567 4.41 4.993-2.646 1.178 1.457-6.493 2.918-1.47-1.818L19.5 2.02zm-14.404 0l4.2 5.753-1.47 1.819-6.548-2.85 1.215-1.502 5.049 2.577L3.92 3.477 5.097 2.02zM11.196 0l1.177 5.552L13.463 0h1.87l-1.821 6.89h-2.336L9.266 0h1.93z"
      fill="#000"
      fillRule="nonzero"
    />
  </Svg>
)

export default Polaris
