/* Generated by scripts/convert-svg from src/assets/icons/ic-money.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Money = (props: IconProps): JSX.Element => (
  <svg width={24} height={24} viewBox="0 0 24 24" {...props}>
    <g strokeWidth={2} fill="none" stroke="#444" strokeLinecap="square" strokeMiterlimit={10}>
      <path d="M1 7h22v16H1z" />
      <circle cx={12} cy={15} r={3} />
      <path data-color="color-2" d="M4 4h16M8 1h8" />
    </g>
  </svg>
)

export default Money
