// Generated by scripts/convert-svg
import BarcodeQr from './barcode-qr'
import Bot from './bot'
import Budgetpath from './budgetpath'
import Budget from './ic-budget'
import Checked from './ic-checked'
import Chevron from './ic-chevron'
import Clothing from './ic-clothing'
import Down from './ic-down'
import Home from './ic-home'
import Menu from './ic-menu'
import Messages from './ic-messages'
import Mic from './ic-mic'
import Money from './ic-money'
import Ob from './ic-ob'
import PinBack from './ic-pin-back'
import Polaris from './ic-polaris'
import Search from './ic-search'
import TouchId from './ic-touch-id'
import Transfer1 from './ic-transfer-1'
import Transfer2 from './ic-transfer-2'
import Transfer3 from './ic-transfer-3'
import Transfer4 from './ic-transfer-4'
import Transfer5 from './ic-transfer-5'
import Transfer6 from './ic-transfer-6'
import X from './ic-x'
import IconQuestionmark from './icon-questionmark'
import Logo from './logo'
import OpenBanking from './open-banking'
import Plus from './plus'
import QuestionMark from './question-mark'
import { IconProps } from './common'

const icons: { name: string; icon: React.ComponentType<IconProps> }[] = [
  {
    name: 'barcode-qr',
    icon: BarcodeQr
  },
  {
    name: 'bot',
    icon: Bot
  },
  {
    name: 'budgetpath',
    icon: Budgetpath
  },
  {
    name: 'ic-budget',
    icon: Budget
  },
  {
    name: 'ic-checked',
    icon: Checked
  },
  {
    name: 'ic-chevron',
    icon: Chevron
  },
  {
    name: 'ic-clothing',
    icon: Clothing
  },
  {
    name: 'ic-down',
    icon: Down
  },
  {
    name: 'ic-home',
    icon: Home
  },
  {
    name: 'ic-menu',
    icon: Menu
  },
  {
    name: 'ic-messages',
    icon: Messages
  },
  {
    name: 'ic-mic',
    icon: Mic
  },
  {
    name: 'ic-money',
    icon: Money
  },
  {
    name: 'ic-ob',
    icon: Ob
  },
  {
    name: 'ic-pin-back',
    icon: PinBack
  },
  {
    name: 'ic-polaris',
    icon: Polaris
  },
  {
    name: 'ic-search',
    icon: Search
  },
  {
    name: 'ic-touch-id',
    icon: TouchId
  },
  {
    name: 'ic-transfer-1',
    icon: Transfer1
  },
  {
    name: 'ic-transfer-2',
    icon: Transfer2
  },
  {
    name: 'ic-transfer-3',
    icon: Transfer3
  },
  {
    name: 'ic-transfer-4',
    icon: Transfer4
  },
  {
    name: 'ic-transfer-5',
    icon: Transfer5
  },
  {
    name: 'ic-transfer-6',
    icon: Transfer6
  },
  {
    name: 'ic-x',
    icon: X
  },
  {
    name: 'icon-questionmark',
    icon: IconQuestionmark
  },
  {
    name: 'logo',
    icon: Logo
  },
  {
    name: 'open-banking',
    icon: OpenBanking
  },
  {
    name: 'plus',
    icon: Plus
  },
  {
    name: 'question-mark',
    icon: QuestionMark
  }
]

export default icons
