/* Generated by scripts/convert-svg from src/assets/icons/bot.svg */
import * as React from 'react'
import { IconProps } from '../common'

const Bot = (props: IconProps): JSX.Element => (
  <svg width={48} height={48} viewBox="0 0 48 48" {...props}>
    <defs>
      <clipPath id="prefix__a">
        <path d="M0 0h48v48H0z" />
      </clipPath>
    </defs>
    <g clipPath="url(#prefix__a)">
      <path fill="#fff" d="M0 0h48v48H0z" />
      <g transform="translate(-1187.776 -289.6)">
        <path d="M1229.777 322.014a17.857 17.857 0 00-16.437-16.628v-4.113a3.8 3.8 0 10-2.537 0v4.115a17.857 17.857 0 00-16.438 16.627l-.045 6.81c3.754 3.635 20.576 15.382 35.457-1.062v-5.749zm-17.706-25.652a1.282 1.282 0 11-1.268 1.28 1.276 1.276 0 011.268-1.28zm-10.76 16.051a15.1 15.1 0 0121.519 0 15.342 15.342 0 014.4 9.6h-30.322a15.356 15.356 0 014.4-9.6zm-4.455 18.324v-6.159h30.429v5.778s-13.68 12.361-30.427.381z" />
        <ellipse
          cx={2.544}
          cy={2.549}
          rx={2.544}
          ry={2.549}
          transform="translate(1209.523 295.087)"
          fill="none"
          stroke="#2165e2"
          strokeWidth={2.3}
        />
        <path d="M1218.41 329.71a1.282 1.282 0 101.268 1.283 1.275 1.275 0 00-1.268-1.283z" fill="#aaa" />
        <path d="M1206.998 316.882a1.282 1.282 0 10-1.267-1.281 1.274 1.274 0 001.267 1.281z" fill="#2165e2" />
        <path
          d="M1223.482 329.71a1.282 1.282 0 101.268 1.283 1.275 1.275 0 00-1.268-1.283zm-17.751 0h-5.071a1.282 1.282 0 000 2.564h5.073a1.282 1.282 0 000-2.564z"
          fill="#aaa"
        />
        <path d="M1217.142 316.882a1.282 1.282 0 10-1.269-1.281 1.274 1.274 0 001.269 1.281z" fill="#2165e2" />
        <circle
          cx={22.64}
          cy={22.64}
          r={22.64}
          transform="translate(1189.176 291)"
          fill="none"
          stroke="#e7e9ec"
          strokeWidth={2}
        />
      </g>
    </g>
  </svg>
)

export default Bot
